/* eslint-disable import/prefer-default-export */
export const abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_factory',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_rewards',
        type: 'address',
      },
      {
        internalType: 'string',
        name: '_infractionData',
        type: 'string',
      },
      {
        internalType: 'string',
        name: '_infractionVideoUrl',
        type: 'string',
      },
      {
        internalType: 'string',
        name: '_infractionDomainUrl',
        type: 'string',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'approvedByComunity',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'approvedByCourt',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'approvedByDepartment',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'claimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'string',
        name: 'url',
        type: 'string',
      },
    ],
    name: 'newProof',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'overduePaimentPeriodEnds',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'paid',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'ready',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'regularPaimentPeriodEnds',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'rejected',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'rejectedByCommunity',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'rejectedByCourt',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'rejectedByDepartment',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'volunteerPaimentPeriodEnds',
    type: 'event',
  },
  {
    inputs: [],
    name: 'factory',
    outputs: [
      {
        internalType: 'contract InfractionFactory',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'infractionData',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'infractionDomainUrl',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'infractionVideoUrl',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'rewards',
    outputs: [
      {
        internalType: 'contract RewardsTandil',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stage',
    outputs: [
      {
        internalType: 'enum Infraction.Stages',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: '_url',
        type: 'string',
      },
    ],
    name: 'addProof',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'setReady',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'communityRejects',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'communityApproves',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'departamentApproves',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'departamentRejects',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'courtApproves',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'courtRejects',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'endVolunteerPayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'endRegularPayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'endOverduePayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'setPaid',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'setClaimed',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'reject',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
